/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* ruby.swg */
/* Implementation : RUBY */
#define SWIGRUBY 1

#include "ruby.h"

/* Flags for pointer conversion */
#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

#define NUM2USHRT(n) (\
    (0 <= NUM2UINT(n) && NUM2UINT(n) <= USHRT_MAX)\
    ? (unsigned short) NUM2UINT(n) \
    : (rb_raise(rb_eArgError, "integer %d out of range of `unsigned short'",\
               NUM2UINT(n)), (short)0)\
)

#define NUM2SHRT(n) (\
    (SHRT_MIN <= NUM2INT(n) && NUM2INT(n) <= SHRT_MAX)\
    ? (short)NUM2INT(n)\
    : (rb_raise(rb_eArgError, "integer %d out of range of `short'",\
               NUM2INT(n)), (short)0)\
)

/* Ruby 1.7 defines NUM2LL(), LL2NUM() and ULL2NUM() macros */
#ifndef NUM2LL
#define NUM2LL(x) NUM2LONG((x))
#endif
#ifndef LL2NUM
#define LL2NUM(x) INT2NUM((long) (x))
#endif
#ifndef ULL2NUM
#define ULL2NUM(x) UINT2NUM((unsigned long) (x))
#endif

/* Ruby 1.7 doesn't (yet) define NUM2ULL() */
#ifndef NUM2ULL
#ifdef HAVE_LONG_LONG
#define NUM2ULL(x) rb_num2ull((x))
#else
#define NUM2ULL(x) NUM2ULONG(x)
#endif
#endif

/*
 * Need to be very careful about how these macros are defined, especially
 * when compiling C++ code or C code with an ANSI C compiler.
 *
 * VALUEFUNC(f) is a macro used to typecast a C function that implements
 * a Ruby method so that it can be passed as an argument to API functions
 * like rb_define_method() and rb_define_singleton_method().
 *
 * VOIDFUNC(f) is a macro used to typecast a C function that implements
 * either the "mark" or "free" stuff for a Ruby Data object, so that it
 * can be passed as an argument to API functions like Data_Wrap_Struct()
 * and Data_Make_Struct().
 */
 
#ifdef __cplusplus
#  ifndef RUBY_METHOD_FUNC /* These definitions should work for Ruby 1.4.6 */
#    define VALUEFUNC(f) ((VALUE (*)()) f)
#    define VOIDFUNC(f)  ((void (*)()) f)
#  else
#    ifndef ANYARGS /* These definitions should work for Ruby 1.6 */
#      define VALUEFUNC(f) ((VALUE (*)()) f)
#      define VOIDFUNC(f)  ((RUBY_DATA_FUNC) f)
#    else /* These definitions should work for Ruby 1.7 */
#      define VALUEFUNC(f) ((VALUE (*)(ANYARGS)) f)
#      define VOIDFUNC(f)  ((RUBY_DATA_FUNC) f)
#    endif
#  endif
#else
#  define VALUEFUNC(f) (f)
#  define VOIDFUNC(f) (f)
#endif

typedef struct {
  VALUE klass;
  VALUE mImpl;
  void  (*mark)(void *);
  void  (*destroy)(void *);
} swig_class;

/* Don't use for expressions have side effect */
#ifndef RB_STRING_VALUE
#define RB_STRING_VALUE(s) (TYPE(s) == T_STRING ? (s) : (*(volatile VALUE *)&(s) = rb_str_to_str(s)))
#endif
#ifndef StringValue
#define StringValue(s) RB_STRING_VALUE(s)
#endif
#ifndef StringValuePtr
#define StringValuePtr(s) RSTRING(RB_STRING_VALUE(s))->ptr
#endif
#ifndef StringValueLen
#define StringValueLen(s) RSTRING(RB_STRING_VALUE(s))->len
#endif
#ifndef SafeStringValue
#define SafeStringValue(v) do {\
    StringValue(v);\
    rb_check_safe_str(v);\
} while (0)
#endif

#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
#define rb_define_alloc_func(klass, func) rb_define_singleton_method((klass), "new", VALUEFUNC((func)), -1)
#define rb_undef_alloc_func(klass) rb_undef_method(CLASS_OF((klass)), "new")
#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { rb_raise(rb_eRuntimeError, (char *) msg ); } else


/*************************************************************** -*- c -*-
 * ruby/precommon.swg
 *
 * Rename all exported symbols from common.swg, to avoid symbol
 * clashes if multiple interpreters are included
 *
 ************************************************************************/

#define SWIG_TypeRegister    SWIG_Ruby_TypeRegister
#define SWIG_TypeCheck       SWIG_Ruby_TypeCheck
#define SWIG_TypeCast        SWIG_Ruby_TypeCast
#define SWIG_TypeDynamicCast SWIG_Ruby_TypeDynamicCast
#define SWIG_TypeName        SWIG_Ruby_TypeName
#define SWIG_TypeQuery       SWIG_Ruby_TypeQuery
#define SWIG_TypeClientData  SWIG_Ruby_TypeClientData
#define SWIG_PackData        SWIG_Ruby_PackData 
#define SWIG_UnpackData      SWIG_Ruby_UnpackData 

/* Also rename all exported symbols from rubydef.swig */

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Ruby_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Ruby_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Ruby_MustGetPtr(p, type, argnum, flags)

/* Ruby-specific SWIG API */

#define SWIG_InitRuntime() \
  SWIG_Ruby_InitRuntime()
#define SWIG_define_class(ty) \
  SWIG_Ruby_define_class(ty)
#define SWIG_NewClassInstance(value, ty) \
  SWIG_Ruby_NewClassInstance(value, ty)
#define SWIG_MangleStr(value) \
  SWIG_Ruby_MangleStr(value)
#define SWIG_CheckConvert(value, ty) \
  SWIG_Ruby_CheckConvert(value, ty)
#define SWIG_NewPackedObj(ptr, sz, ty) \
  SWIG_Ruby_NewPackedObj(ptr, sz, ty)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Ruby_ConvertPacked(obj, ptr, sz, ty, flags)


/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if defined(_MSC_VER) || defined(__GNUC__)
#    if defined(STATIC_LINKED)
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) extern a
#    else
#      define SWIGEXPORT(a) __declspec(dllexport) a
#      define SWIGIMPORT(a) extern a
#    endif
#  else
#    if defined(__BORLANDC__)
#      define SWIGEXPORT(a) a _export
#      define SWIGIMPORT(a) a _export
#    else
#      define SWIGEXPORT(a) a
#      define SWIGIMPORT(a) a
#    endif
#  endif
#else
#  define SWIGEXPORT(a) a
#  define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#  define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#  define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);
SWIGIMPORT(char *)           SWIG_PackData(char *, void *, int);
SWIGIMPORT(char *)           SWIG_UnpackData(char *, void *, int);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientData(tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

#endif

#ifdef __cplusplus
}
#endif

/* rubydef.swg */
#ifdef __cplusplus
extern "C" {
#endif

static VALUE _mSWIG = Qnil;
static VALUE _cSWIG_Pointer = Qnil;

/* Initialize Ruby runtime support */
SWIGRUNTIME(void)
SWIG_Ruby_InitRuntime(void)
{
    if (_mSWIG == Qnil) {
        _mSWIG = rb_define_module("SWIG");
    }
}

/* Define Ruby class for C type */
SWIGRUNTIME(void)
SWIG_Ruby_define_class(swig_type_info *type)
{
    VALUE klass;
    char *klass_name = (char *) malloc(4 + strlen(type->name) + 1);
    sprintf(klass_name, "TYPE%s", type->name);
    if (NIL_P(_cSWIG_Pointer)) {
	_cSWIG_Pointer = rb_define_class_under(_mSWIG, "Pointer", rb_cObject);
	rb_undef_method(CLASS_OF(_cSWIG_Pointer), "new");
    }
    klass = rb_define_class_under(_mSWIG, klass_name, _cSWIG_Pointer);
    free((void *) klass_name);
}

/* Create a new pointer object */
SWIGRUNTIME(VALUE)
SWIG_Ruby_NewPointerObj(void *ptr, swig_type_info *type, int own)
{
    char *klass_name;
    swig_class *sklass;
    VALUE klass;
    VALUE obj;
    
    if (!ptr)
	return Qnil;
    
    if (type->clientdata) {
      sklass = (swig_class *) type->clientdata;
      obj = Data_Wrap_Struct(sklass->klass, VOIDFUNC(sklass->mark), (own ? VOIDFUNC(sklass->destroy) : 0), ptr);
    } else {
      klass_name = (char *) malloc(4 + strlen(type->name) + 1);
      sprintf(klass_name, "TYPE%s", type->name);
      klass = rb_const_get(_mSWIG, rb_intern(klass_name));
      free((void *) klass_name);
      obj = Data_Wrap_Struct(klass, 0, 0, ptr);
    }
    rb_iv_set(obj, "__swigtype__", rb_str_new2(type->name));
    return obj;
}

/* Create a new class instance (always owned) */
SWIGRUNTIME(VALUE)
SWIG_Ruby_NewClassInstance(VALUE klass, swig_type_info *type)
{
    VALUE obj;
    swig_class *sklass = (swig_class *) type->clientdata;
    obj = Data_Wrap_Struct(klass, VOIDFUNC(sklass->mark), VOIDFUNC(sklass->destroy), 0);
    rb_iv_set(obj, "__swigtype__", rb_str_new2(type->name));
    return obj;
}

/* Get type mangle from class name */
SWIGRUNTIME(char *)
SWIG_Ruby_MangleStr(VALUE obj)
{
  VALUE stype = rb_iv_get(obj, "__swigtype__");
  return StringValuePtr(stype);
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_Ruby_ConvertPtr(VALUE obj, void **ptr, swig_type_info *ty, int flags)
{
  char *c;
  swig_type_info *tc;

  /* Grab the pointer */
  if (NIL_P(obj)) {
    *ptr = 0;
    return 0;
  } else {
    Data_Get_Struct(obj, void, *ptr);
  }
  
  /* Do type-checking if type info was provided */
  if (ty) {
    if (ty->clientdata) {
        if (rb_obj_is_kind_of(obj, ((swig_class *) (ty->clientdata))->klass)) {
          if (*ptr == 0)
            rb_raise(rb_eRuntimeError, "This %s already released", ty->str);
          return 0;
        }
    }
    if ((c = SWIG_MangleStr(obj)) == NULL) {
      if (flags & SWIG_POINTER_EXCEPTION)
        rb_raise(rb_eTypeError, "Expected %s", ty->str);
      else
        return -1;
    }
    tc = SWIG_TypeCheck(c, ty);
    if (!tc) {
      if (flags & SWIG_POINTER_EXCEPTION)
        rb_raise(rb_eTypeError, "Expected %s", ty->str);
      else
        return -1;
    }
    *ptr = SWIG_TypeCast(tc, *ptr);
  }
  return 0;
}

/* Convert a pointer value, signal an exception on a type mismatch */
SWIGRUNTIME(void *)
SWIG_Ruby_MustGetPtr(VALUE obj, swig_type_info *ty, int argnum, int flags)
{
  void *result;
  SWIG_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Check convert */
SWIGRUNTIME(int)
SWIG_Ruby_CheckConvert(VALUE obj, swig_type_info *ty)
{
  char *c = SWIG_MangleStr(obj);
  if (!c)
    return 0;
  return SWIG_TypeCheck(c,ty) != 0;
}

SWIGRUNTIME(VALUE)
SWIG_Ruby_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r, ptr, sz);
  strcpy(r, type->name);
  return rb_str_new2(result);
}

/* Convert a packed value value */
SWIGRUNTIME(void)
SWIG_Ruby_ConvertPacked(VALUE obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if (TYPE(obj) != T_STRING) goto type_error;
  c = StringValuePtr(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c, ptr, sz);
  if (ty) {
    tc = SWIG_TypeCheck(c, ty);
    if (!tc) goto type_error;
  }
  return;

type_error:

  if (flags) {
    if (ty) {
      rb_raise(rb_eTypeError, "Type error. Expected %s", ty->name);
    } else {
      rb_raise(rb_eTypeError, "Expected a pointer");
    }
  }
}

#ifdef __cplusplus
}
#endif



/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_exit_status swig_types[0] 
#define  SWIGTYPE_p_utmp swig_types[1] 
#define  SWIGTYPE_p_char swig_types[2] 
#define  SWIGTYPE_p_utmp_ut_tv swig_types[3] 
#define  SWIGTYPE_p_lastlog swig_types[4] 
static swig_type_info *swig_types[6];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    Init_rutmp
#define SWIG_name    "Rutmp"

static VALUE mRutmp;

#include <utmp.h>


swig_class cLastlog;
static void free_lastlog(struct lastlog *);

swig_class cExit_status;
static void free_exit_status(struct exit_status *);

typedef struct {
    int tv_sec;		/* Seconds.  */
    int tv_usec;		/* Microseconds.  */
  } utmp_ut_tv;



swig_class cUtmp;
static void free_utmp(struct utmp *);

swig_class cUtmp_ut_tv;
static void free_utmp_ut_tv(utmp_ut_tv *);
extern int login_tty(int);
extern void login(struct utmp const *);
extern int logout(char const *);
extern void logwtmp(char const *,char const *,char const *);
extern void updwtmp(char const *,struct utmp const *);
extern int utmpname(char const *);
extern struct utmp *getutent(void);
extern void setutent(void);
extern void endutent(void);
extern struct utmp *getutid(struct utmp const *);
extern struct utmp *getutline(struct utmp const *);
extern struct utmp *pututline(struct utmp const *);
static VALUE
_wrap_lastlog_ll_time_set(int argc, VALUE *argv, VALUE self) {
    struct lastlog *arg1 = (struct lastlog *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_lastlog, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->ll_time = arg2;
    
    return Qnil;
}


static VALUE
_wrap_lastlog_ll_time_get(int argc, VALUE *argv, VALUE self) {
    struct lastlog *arg1 = (struct lastlog *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_lastlog, 1);
    result = (int) ((arg1)->ll_time);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_lastlog_ll_line_set(int argc, VALUE *argv, VALUE self) {
    struct lastlog *arg1 = (struct lastlog *) 0 ;
    char *arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_lastlog, 1);
    arg2 = StringValuePtr(argv[0]);
    {
        if (arg2) strncpy(arg1->ll_line,arg2,32);
        else arg1->ll_line[0] = 0;
    }
    return Qnil;
}


static VALUE
_wrap_lastlog_ll_line_get(int argc, VALUE *argv, VALUE self) {
    struct lastlog *arg1 = (struct lastlog *) 0 ;
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_lastlog, 1);
    result = (char *)(char *) ((arg1)->ll_line);
    
    vresult = rb_str_new2(result);
    return vresult;
}


static VALUE
_wrap_lastlog_ll_host_set(int argc, VALUE *argv, VALUE self) {
    struct lastlog *arg1 = (struct lastlog *) 0 ;
    char *arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_lastlog, 1);
    arg2 = StringValuePtr(argv[0]);
    {
        if (arg2) strncpy(arg1->ll_host,arg2,256);
        else arg1->ll_host[0] = 0;
    }
    return Qnil;
}


static VALUE
_wrap_lastlog_ll_host_get(int argc, VALUE *argv, VALUE self) {
    struct lastlog *arg1 = (struct lastlog *) 0 ;
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_lastlog, 1);
    result = (char *)(char *) ((arg1)->ll_host);
    
    vresult = rb_str_new2(result);
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_lastlog_allocate(VALUE self) {
#else
    static VALUE
    _wrap_lastlog_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_lastlog);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_lastlog(int argc, VALUE *argv, VALUE self) {
    struct lastlog *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (struct lastlog *)(struct lastlog *) calloc(1, sizeof(struct lastlog));
    DATA_PTR(self) = result;
    return self;
}


static void
free_lastlog(struct lastlog *arg1) {
    free((char*) arg1);
}
static VALUE
_wrap_exit_status_e_termination_set(int argc, VALUE *argv, VALUE self) {
    struct exit_status *arg1 = (struct exit_status *) 0 ;
    short arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_exit_status, 1);
    arg2 = NUM2SHRT(argv[0]);
    if (arg1) (arg1)->e_termination = arg2;
    
    return Qnil;
}


static VALUE
_wrap_exit_status_e_termination_get(int argc, VALUE *argv, VALUE self) {
    struct exit_status *arg1 = (struct exit_status *) 0 ;
    short result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_exit_status, 1);
    result = (short) ((arg1)->e_termination);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_exit_status_e_exit_set(int argc, VALUE *argv, VALUE self) {
    struct exit_status *arg1 = (struct exit_status *) 0 ;
    short arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_exit_status, 1);
    arg2 = NUM2SHRT(argv[0]);
    if (arg1) (arg1)->e_exit = arg2;
    
    return Qnil;
}


static VALUE
_wrap_exit_status_e_exit_get(int argc, VALUE *argv, VALUE self) {
    struct exit_status *arg1 = (struct exit_status *) 0 ;
    short result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_exit_status, 1);
    result = (short) ((arg1)->e_exit);
    
    vresult = INT2NUM(result);
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_exit_status_allocate(VALUE self) {
#else
    static VALUE
    _wrap_exit_status_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_exit_status);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_exit_status(int argc, VALUE *argv, VALUE self) {
    struct exit_status *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (struct exit_status *)(struct exit_status *) calloc(1, sizeof(struct exit_status));
    DATA_PTR(self) = result;
    return self;
}


static void
free_exit_status(struct exit_status *arg1) {
    free((char*) arg1);
}
static VALUE
_wrap_utmp_ut_type_set(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    short arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    arg2 = NUM2SHRT(argv[0]);
    if (arg1) (arg1)->ut_type = arg2;
    
    return Qnil;
}


static VALUE
_wrap_utmp_ut_type_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    short result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (short) ((arg1)->ut_type);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_utmp_ut_pid_set(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->ut_pid = arg2;
    
    return Qnil;
}


static VALUE
_wrap_utmp_ut_pid_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (int) ((arg1)->ut_pid);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_utmp_ut_line_set(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    char *arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    arg2 = StringValuePtr(argv[0]);
    {
        if (arg2) strncpy(arg1->ut_line,arg2,32);
        else arg1->ut_line[0] = 0;
    }
    return Qnil;
}


static VALUE
_wrap_utmp_ut_line_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (char *)(char *) ((arg1)->ut_line);
    
    vresult = rb_str_new2(result);
    return vresult;
}


static VALUE
_wrap_utmp_ut_id_set(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    char *arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    arg2 = StringValuePtr(argv[0]);
    {
        if (arg2) strncpy(arg1->ut_id,arg2,4);
        else arg1->ut_id[0] = 0;
    }
    return Qnil;
}


static VALUE
_wrap_utmp_ut_id_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (char *)(char *) ((arg1)->ut_id);
    
    vresult = rb_str_new2(result);
    return vresult;
}


static VALUE
_wrap_utmp_ut_user_set(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    char *arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    arg2 = StringValuePtr(argv[0]);
    {
        if (arg2) strncpy(arg1->ut_user,arg2,32);
        else arg1->ut_user[0] = 0;
    }
    return Qnil;
}


static VALUE
_wrap_utmp_ut_user_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (char *)(char *) ((arg1)->ut_user);
    
    vresult = rb_str_new2(result);
    return vresult;
}


static VALUE
_wrap_utmp_ut_host_set(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    char *arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    arg2 = StringValuePtr(argv[0]);
    {
        if (arg2) strncpy(arg1->ut_host,arg2,256);
        else arg1->ut_host[0] = 0;
    }
    return Qnil;
}


static VALUE
_wrap_utmp_ut_host_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (char *)(char *) ((arg1)->ut_host);
    
    vresult = rb_str_new2(result);
    return vresult;
}


static VALUE
_wrap_utmp_ut_exit_set(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    struct exit_status *arg2 = (struct exit_status *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    SWIG_ConvertPtr(argv[0], (void **) &arg2, SWIGTYPE_p_exit_status, 1);
    if (arg1) (arg1)->ut_exit = *arg2;
    
    return Qnil;
}


static VALUE
_wrap_utmp_ut_exit_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    struct exit_status *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (struct exit_status *)& ((arg1)->ut_exit);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_exit_status,0);
    return vresult;
}


static VALUE
_wrap_utmp_ut_session_set(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->ut_session = arg2;
    
    return Qnil;
}


static VALUE
_wrap_utmp_ut_session_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (int) ((arg1)->ut_session);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_utmp_ut_addr_set(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->ut_addr = arg2;
    
    return Qnil;
}


static VALUE
_wrap_utmp_ut_addr_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (int) ((arg1)->ut_addr);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_utmp_ut_tv_get(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    utmp_ut_tv *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (utmp_ut_tv *)& ((arg1)->ut_tv);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_utmp_ut_tv,0);
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_utmp_allocate(VALUE self) {
#else
    static VALUE
    _wrap_utmp_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_utmp);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_utmp(int argc, VALUE *argv, VALUE self) {
    struct utmp *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (struct utmp *)(struct utmp *) calloc(1, sizeof(struct utmp));
    DATA_PTR(self) = result;
    return self;
}


static void
free_utmp(struct utmp *arg1) {
    free((char*) arg1);
}
static VALUE
_wrap_utmp_ut_tv_tv_sec_set(int argc, VALUE *argv, VALUE self) {
    utmp_ut_tv *arg1 = (utmp_ut_tv *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp_ut_tv, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->tv_sec = arg2;
    
    return Qnil;
}


static VALUE
_wrap_utmp_ut_tv_tv_sec_get(int argc, VALUE *argv, VALUE self) {
    utmp_ut_tv *arg1 = (utmp_ut_tv *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp_ut_tv, 1);
    result = (int) ((arg1)->tv_sec);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_utmp_ut_tv_tv_usec_set(int argc, VALUE *argv, VALUE self) {
    utmp_ut_tv *arg1 = (utmp_ut_tv *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp_ut_tv, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->tv_usec = arg2;
    
    return Qnil;
}


static VALUE
_wrap_utmp_ut_tv_tv_usec_get(int argc, VALUE *argv, VALUE self) {
    utmp_ut_tv *arg1 = (utmp_ut_tv *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_utmp_ut_tv, 1);
    result = (int) ((arg1)->tv_usec);
    
    vresult = INT2NUM(result);
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_utmp_ut_tv_allocate(VALUE self) {
#else
    static VALUE
    _wrap_utmp_ut_tv_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_utmp_ut_tv);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_utmp_ut_tv(int argc, VALUE *argv, VALUE self) {
    utmp_ut_tv *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (utmp_ut_tv *)(utmp_ut_tv *) calloc(1, sizeof(utmp_ut_tv));
    DATA_PTR(self) = result;
    return self;
}


static void
free_utmp_ut_tv(utmp_ut_tv *arg1) {
    free((char*) arg1);
}
static VALUE
_wrap_login_tty(int argc, VALUE *argv, VALUE self) {
    int arg1 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    arg1 = NUM2INT(argv[0]);
    result = (int)login_tty(arg1);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_login(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(argv[0], (void **) &arg1, SWIGTYPE_p_utmp, 1);
    login((struct utmp const *)arg1);
    
    return Qnil;
}


static VALUE
_wrap_logout(int argc, VALUE *argv, VALUE self) {
    char *arg1 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    arg1 = StringValuePtr(argv[0]);
    result = (int)logout((char const *)arg1);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_logwtmp(int argc, VALUE *argv, VALUE self) {
    char *arg1 ;
    char *arg2 ;
    char *arg3 ;
    
    if ((argc < 3) || (argc > 3))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 3)",argc);
    arg1 = StringValuePtr(argv[0]);
    arg2 = StringValuePtr(argv[1]);
    arg3 = StringValuePtr(argv[2]);
    logwtmp((char const *)arg1,(char const *)arg2,(char const *)arg3);
    
    return Qnil;
}


static VALUE
_wrap_updwtmp(int argc, VALUE *argv, VALUE self) {
    char *arg1 ;
    struct utmp *arg2 = (struct utmp *) 0 ;
    
    if ((argc < 2) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 2)",argc);
    arg1 = StringValuePtr(argv[0]);
    SWIG_ConvertPtr(argv[1], (void **) &arg2, SWIGTYPE_p_utmp, 1);
    updwtmp((char const *)arg1,(struct utmp const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_utmpname(int argc, VALUE *argv, VALUE self) {
    char *arg1 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    arg1 = StringValuePtr(argv[0]);
    result = (int)utmpname((char const *)arg1);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_getutent(int argc, VALUE *argv, VALUE self) {
    struct utmp *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (struct utmp *)getutent();
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_utmp,0);
    return vresult;
}


static VALUE
_wrap_setutent(int argc, VALUE *argv, VALUE self) {
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    setutent();
    
    return Qnil;
}


static VALUE
_wrap_endutent(int argc, VALUE *argv, VALUE self) {
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    endutent();
    
    return Qnil;
}


static VALUE
_wrap_getutid(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    struct utmp *result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(argv[0], (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (struct utmp *)getutid((struct utmp const *)arg1);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_utmp,0);
    return vresult;
}


static VALUE
_wrap_getutline(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    struct utmp *result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(argv[0], (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (struct utmp *)getutline((struct utmp const *)arg1);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_utmp,0);
    return vresult;
}


static VALUE
_wrap_pututline(int argc, VALUE *argv, VALUE self) {
    struct utmp *arg1 = (struct utmp *) 0 ;
    struct utmp *result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(argv[0], (void **) &arg1, SWIGTYPE_p_utmp, 1);
    result = (struct utmp *)pututline((struct utmp const *)arg1);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_utmp,0);
    return vresult;
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_exit_status[] = {{"_p_exit_status", 0, "struct exit_status *", 0},{"_p_exit_status"},{0}};
static swig_type_info _swigt__p_utmp[] = {{"_p_utmp", 0, "struct utmp *", 0},{"_p_utmp"},{0}};
static swig_type_info _swigt__p_char[] = {{"_p_char", 0, "char *", 0},{"_p_char"},{0}};
static swig_type_info _swigt__p_utmp_ut_tv[] = {{"_p_utmp_ut_tv", 0, "utmp_ut_tv *", 0},{"_p_utmp_ut_tv"},{0}};
static swig_type_info _swigt__p_lastlog[] = {{"_p_lastlog", 0, "struct lastlog *", 0},{"_p_lastlog"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_exit_status, 
_swigt__p_utmp, 
_swigt__p_char, 
_swigt__p_utmp_ut_tv, 
_swigt__p_lastlog, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */


#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) Init_rutmp(void) {
    int i;
    
    SWIG_InitRuntime();
    mRutmp = rb_define_module("Rutmp");
    
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        SWIG_define_class(swig_types[i]);
    }
    
    rb_define_const(mRutmp,"UT_LINESIZE", INT2NUM(32));
    rb_define_const(mRutmp,"UT_NAMESIZE", INT2NUM(32));
    rb_define_const(mRutmp,"UT_HOSTSIZE", INT2NUM(256));
    
    cLastlog.klass = rb_define_class_under(mRutmp, "Lastlog", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_lastlog, (void *) &cLastlog);
    rb_define_alloc_func(cLastlog.klass, _wrap_lastlog_allocate);
    rb_define_method(cLastlog.klass, "initialize", _wrap_new_lastlog, -1);
    rb_define_method(cLastlog.klass, "ll_time=", _wrap_lastlog_ll_time_set, -1);
    rb_define_method(cLastlog.klass, "ll_time", _wrap_lastlog_ll_time_get, -1);
    rb_define_method(cLastlog.klass, "ll_line=", _wrap_lastlog_ll_line_set, -1);
    rb_define_method(cLastlog.klass, "ll_line", _wrap_lastlog_ll_line_get, -1);
    rb_define_method(cLastlog.klass, "ll_host=", _wrap_lastlog_ll_host_set, -1);
    rb_define_method(cLastlog.klass, "ll_host", _wrap_lastlog_ll_host_get, -1);
    cLastlog.mark = 0;
    cLastlog.destroy = (void (*)(void *)) free_lastlog;
    
    cExit_status.klass = rb_define_class_under(mRutmp, "Exit_status", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_exit_status, (void *) &cExit_status);
    rb_define_alloc_func(cExit_status.klass, _wrap_exit_status_allocate);
    rb_define_method(cExit_status.klass, "initialize", _wrap_new_exit_status, -1);
    rb_define_method(cExit_status.klass, "e_termination=", _wrap_exit_status_e_termination_set, -1);
    rb_define_method(cExit_status.klass, "e_termination", _wrap_exit_status_e_termination_get, -1);
    rb_define_method(cExit_status.klass, "e_exit=", _wrap_exit_status_e_exit_set, -1);
    rb_define_method(cExit_status.klass, "e_exit", _wrap_exit_status_e_exit_get, -1);
    cExit_status.mark = 0;
    cExit_status.destroy = (void (*)(void *)) free_exit_status;
    
    cUtmp.klass = rb_define_class_under(mRutmp, "Utmp", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_utmp, (void *) &cUtmp);
    rb_define_alloc_func(cUtmp.klass, _wrap_utmp_allocate);
    rb_define_method(cUtmp.klass, "initialize", _wrap_new_utmp, -1);
    rb_define_method(cUtmp.klass, "ut_type=", _wrap_utmp_ut_type_set, -1);
    rb_define_method(cUtmp.klass, "ut_type", _wrap_utmp_ut_type_get, -1);
    rb_define_method(cUtmp.klass, "ut_pid=", _wrap_utmp_ut_pid_set, -1);
    rb_define_method(cUtmp.klass, "ut_pid", _wrap_utmp_ut_pid_get, -1);
    rb_define_method(cUtmp.klass, "ut_line=", _wrap_utmp_ut_line_set, -1);
    rb_define_method(cUtmp.klass, "ut_line", _wrap_utmp_ut_line_get, -1);
    rb_define_method(cUtmp.klass, "ut_id=", _wrap_utmp_ut_id_set, -1);
    rb_define_method(cUtmp.klass, "ut_id", _wrap_utmp_ut_id_get, -1);
    rb_define_method(cUtmp.klass, "ut_user=", _wrap_utmp_ut_user_set, -1);
    rb_define_method(cUtmp.klass, "ut_user", _wrap_utmp_ut_user_get, -1);
    rb_define_method(cUtmp.klass, "ut_host=", _wrap_utmp_ut_host_set, -1);
    rb_define_method(cUtmp.klass, "ut_host", _wrap_utmp_ut_host_get, -1);
    rb_define_method(cUtmp.klass, "ut_exit=", _wrap_utmp_ut_exit_set, -1);
    rb_define_method(cUtmp.klass, "ut_exit", _wrap_utmp_ut_exit_get, -1);
    rb_define_method(cUtmp.klass, "ut_session=", _wrap_utmp_ut_session_set, -1);
    rb_define_method(cUtmp.klass, "ut_session", _wrap_utmp_ut_session_get, -1);
    rb_define_method(cUtmp.klass, "ut_addr=", _wrap_utmp_ut_addr_set, -1);
    rb_define_method(cUtmp.klass, "ut_addr", _wrap_utmp_ut_addr_get, -1);
    rb_define_method(cUtmp.klass, "ut_tv", _wrap_utmp_ut_tv_get, -1);
    cUtmp.mark = 0;
    cUtmp.destroy = (void (*)(void *)) free_utmp;
    
    cUtmp_ut_tv.klass = rb_define_class_under(mRutmp, "Utmp_ut_tv", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_utmp_ut_tv, (void *) &cUtmp_ut_tv);
    rb_define_alloc_func(cUtmp_ut_tv.klass, _wrap_utmp_ut_tv_allocate);
    rb_define_method(cUtmp_ut_tv.klass, "initialize", _wrap_new_utmp_ut_tv, -1);
    rb_define_method(cUtmp_ut_tv.klass, "tv_sec=", _wrap_utmp_ut_tv_tv_sec_set, -1);
    rb_define_method(cUtmp_ut_tv.klass, "tv_sec", _wrap_utmp_ut_tv_tv_sec_get, -1);
    rb_define_method(cUtmp_ut_tv.klass, "tv_usec=", _wrap_utmp_ut_tv_tv_usec_set, -1);
    rb_define_method(cUtmp_ut_tv.klass, "tv_usec", _wrap_utmp_ut_tv_tv_usec_get, -1);
    cUtmp_ut_tv.mark = 0;
    cUtmp_ut_tv.destroy = (void (*)(void *)) free_utmp_ut_tv;
    rb_define_const(mRutmp,"EMPTY", INT2NUM(0));
    rb_define_const(mRutmp,"RUN_LVL", INT2NUM(1));
    rb_define_const(mRutmp,"BOOT_TIME", INT2NUM(2));
    rb_define_const(mRutmp,"NEW_TIME", INT2NUM(3));
    rb_define_const(mRutmp,"OLD_TIME", INT2NUM(4));
    rb_define_const(mRutmp,"INIT_PROCESS", INT2NUM(5));
    rb_define_const(mRutmp,"LOGIN_PROCESS", INT2NUM(6));
    rb_define_const(mRutmp,"USER_PROCESS", INT2NUM(7));
    rb_define_const(mRutmp,"DEAD_PROCESS", INT2NUM(8));
    rb_define_const(mRutmp,"ACCOUNTING", INT2NUM(9));
    rb_define_const(mRutmp,"UT_UNKNOWN", INT2NUM(0));
    rb_define_module_function(mRutmp, "login_tty", _wrap_login_tty, -1);
    rb_define_module_function(mRutmp, "login", _wrap_login, -1);
    rb_define_module_function(mRutmp, "logout", _wrap_logout, -1);
    rb_define_module_function(mRutmp, "logwtmp", _wrap_logwtmp, -1);
    rb_define_module_function(mRutmp, "updwtmp", _wrap_updwtmp, -1);
    rb_define_module_function(mRutmp, "utmpname", _wrap_utmpname, -1);
    rb_define_module_function(mRutmp, "getutent", _wrap_getutent, -1);
    rb_define_module_function(mRutmp, "setutent", _wrap_setutent, -1);
    rb_define_module_function(mRutmp, "endutent", _wrap_endutent, -1);
    rb_define_module_function(mRutmp, "getutid", _wrap_getutid, -1);
    rb_define_module_function(mRutmp, "getutline", _wrap_getutline, -1);
    rb_define_module_function(mRutmp, "pututline", _wrap_pututline, -1);
}

